#define main legacy_acceptance_main
#include "native_sparse_gnss.cpp"
#undef main
Fixture xy_fixture(bool xy,bool sparse=true){Fixture f(sparse);auto c=settings(sparse);c.gnss_xy_residual_correction=xy;f.pipe=Pipeline(c,{f.route});return f;}
int main(){
 legacy_acceptance_main();
 for(int channel=0;channel<2;++channel)test(channel?"XY single rover cross3":"XY single master cross3",[channel]{auto a=xy_fixture(false),b=xy_fixture(true);a.through(79);b.through(79);I t=T0+80*DT;auto fix=b.fix_lla(channel,t,0.,3.);require(a.pipe.fix(channel,t,t,fix)&&b.pipe.fix(channel,t,t,fix),"fix accepted");auto x=a.tick(80),y=b.tick(80);near(y.position[1]-x.position[1],.75,1e-6,"cross3 quarter update");near(y.route_s-x.route_s,0.,1e-6,"cross residual must not change phase");near(y.position[2],x.position[2],1e-12,"Z unchanged");speed_unchanged(x,y);require(y.gnss_accepted==1,"new fix counted");});
 test("XY29m residual capped at5m old mode rejects",[]{auto a=xy_fixture(false),b=xy_fixture(true);a.through(79);b.through(79);I t=T0+80*DT;auto fix=b.fix_lla(0,t,0.,29.);a.pipe.fix(0,t,t,fix);b.pipe.fix(0,t,t,fix);auto x=a.tick(80),y=b.tick(80);near(y.position[1]-x.position[1],5.,1e-8,"XY vector step cap");require(x.gnss_rejected==1&&x.gnss_accepted==0&&y.gnss_accepted==1,"mode-dependent residual gates");speed_unchanged(x,y);});
 test("XY outlier31m rejected",[]{auto a=xy_fixture(false),b=xy_fixture(true);a.through(79);b.through(79);I t=T0+80*DT;b.pipe.fix(0,t,t,b.fix_lla(0,t,0.,31.));auto x=a.tick(80),y=b.tick(80);require(x.position==y.position&&y.gnss_rejected==1&&y.gnss_accepted==0,"31m XY outlier accepted");speed_unchanged(x,y);});
 test("XY stale future status reject",[]{auto a=xy_fixture(false),b=xy_fixture(true);a.through(99);b.through(99);I t=T0+100*DT;require(!b.pipe.fix(0,t+50000001,t,b.fix_lla(0,t,0.,3.)),"future accepted");require(!b.pipe.fix(0,t,t,b.fix_lla(0,t,0.,3.),-1),"invalid status accepted");I old=t-1000000001;require(!b.pipe.fix(0,old,t,b.fix_lla(0,old,0.,3.)),"stale accepted");auto x=a.tick(100),y=b.tick(100);require(x.position==y.position&&y.gnss_accepted==0,"bad fix moved XY");});
 test("XY feature does nothing when sparse correction off",[]{auto a=xy_fixture(false,false),b=xy_fixture(true,false);a.through(79);b.through(79);I t=T0+80*DT;require(!a.pipe.fix(0,t,t,a.fix_lla(0,t,0.,3.))&&!b.pipe.fix(0,t,t,b.fix_lla(0,t,0.,3.)),"disabled sparse accepted fix");auto x=a.tick(80),y=b.tick(80);require(x.position==y.position&&x.route_s==y.route_s,"disabled sparse differs");speed_unchanged(x,y);});
 test("XY independent along and lateral5m caps",[]{auto a=xy_fixture(false),b=xy_fixture(true);a.through(79);b.through(79);I t=T0+80*DT;b.pipe.fix(0,t,t,b.fix_lla(0,t,20.,20.));auto x=a.tick(80),y=b.tick(80);near(y.route_s-x.route_s,5.,1e-5,"along cap");near(y.position[1]-x.position[1],5.,1e-5,"cross cap");near(norm(sub(y.position,x.position)),std::sqrt(50.),2e-5,"combined jump explicitly sqrt50");speed_unchanged(x,y);});
 test("XY reset clears map translation",[]{auto a=xy_fixture(false),b=xy_fixture(true);b.through(79);I t=T0+80*DT;b.pipe.fix(0,t,t,b.fix_lla(0,t,0.,3.));b.tick(80);b.pipe.reset();b.index=-1;a.through(79);b.through(79);require(a.last.position==b.last.position&&b.last.gnss_accepted==0,"XY translation survived reset");});

 test("XY decay exactly exp(-100m/100m)",[]{auto a=xy_fixture(false),b=xy_fixture(true);a.through(79);b.through(79);I t=T0+80*DT;b.pipe.fix(0,t,t,b.fix_lla(0,t,0.,3.));auto x=a.tick(80),y=b.tick(80);double initial=y.position[1]-x.position[1],d0=y.distance;near(initial,.75,1e-6,"initial shift");a.through(480);b.through(480);near(b.last.distance-d0,100.,1e-8,"analytic100m trajectory");near(b.last.position[1]-a.last.position[1],initial/std::exp(1.),1e-8,"100m must divide bias by e");speed_unchanged(a.last,b.last);near(b.last.position[2],a.last.position[2],1e-12,"no Z bias");});
 test("XY decay freezes at standstill",[]{auto a=xy_fixture(false),b=xy_fixture(true);a.through(79);b.through(79);I t=T0+80*DT;b.pipe.fix(0,t,t,b.fix_lla(0,t,0.,3.));a.tick(80);b.tick(80);double bias=.75,d0=b.last.distance,stationary_bias=0.,stationary_distance=0.;for(int i=81;i<=300;++i){I stamp=T0+i*DT;for(auto*f:{&a,&b}){for(int c=0;c<2;++c)require(f->pipe.wheel(c,stamp,0.,stamp),"stationary wheel");require(f->pipe.command(stamp,0,stamp),"stationary command");require(f->pipe.step(stamp,stamp,f->last),"stationary output");}speed_unchanged(a.last,b.last);near(b.last.position[1]-a.last.position[1],bias*std::exp(-(b.last.distance-d0)/100.),1e-6,"distance-only decay during stop");if(i==250){stationary_bias=b.last.position[1]-a.last.position[1];stationary_distance=b.last.distance;}}near(b.last.distance,stationary_distance,1e-12,"vehicle stopped by250");near(b.last.position[1]-a.last.position[1],stationary_bias,1e-12,"no wall-time decay at standstill");});
 test("XY decay preserves permanent initial alignment",[]{auto a=xy_fixture(false),b=xy_fixture(true);auto ca=settings(true),cb=settings(true);ca.align_initial_position=cb.align_initial_position=true;cb.gnss_xy_residual_correction=true;a.pipe=Pipeline(ca,{a.route});b.pipe=Pipeline(cb,{b.route});double d0=0.;for(int i=0;i<=480;++i){I stamp=T0+i*DT;if(i<=56&&i%2==0)for(auto*f:{&a,&b})for(int c=0;c<2;++c)require(f->pipe.fix(c,stamp,stamp,f->fix_lla(c,stamp,0.,4.)),"shifted startup");if(i==80)require(b.pipe.fix(0,stamp,stamp,b.fix_lla(0,stamp,0.,7.)),"later residual");auto x=a.tick(i,false),y=b.tick(i,false);speed_unchanged(x,y);if(i==80){near(y.position[1]-x.position[1],.75,1e-6,"shifted cross3");d0=y.distance;}}near(a.last.position[1],4.,1e-6,"initial alignment survives100m");near(b.last.position[1]-a.last.position[1],.75*std::exp(-(b.last.distance-d0)/100.),1e-6,"only learned bias decays");});
 test("legacy sparse-disabled missing initialization stays frozen",[]{Fixture b(false);for(int i=0;i<=80;++i)b.tick(i,false);I t=T0+81*DT;require(b.pipe.frozen()&&!b.pipe.fix(0,t,t,b.fix_lla(0,t)),"legacy sparse-off changed");});
 test("retry reset clears pending window",[]{Fixture b(true);for(int i=0;i<=80;++i)b.tick(i,false);I t=T0+81*DT;require(b.pipe.fix(0,t,t,b.fix_lla(0,t)),"retry should queue");b.pipe.reset();b.index=-1;b.through(79);require(b.last.initialized&&b.pipe.frozen(),"reset left retry state");});
 std::cout<<"XY_RESULT failures="<<failures<<'\n';return failures?1:0;
}
