#define main legacy_acceptance_main
#include "../native_sparse_gnss.cpp"
#undef main
Fixture offmap(double departure,double limit=100.){Fixture f(true);auto c=settings(true);c.gnss_xy_residual_correction=true;c.offmap_departure=departure;c.offmap_max_distance=limit;f.pipe=Pipeline(c,{f.route});return f;}
Vec3 branch(const Fixture&f,I fork,I t,double x){double s=5.*double(t-fork)*1e-9,a=30.*PI/180.;auto base=f.route.pose(f.start+5.*double(fork-T0)*1e-9).position;Vec3 d{{std::cos(a),std::sin(a),0.}};return add(base,add(mul(d,s+x),Vec3{{0,0,x==0.?0.:3.}}));}
Output drive_branch(Fixture&f,int first,int last,bool fixes=true,int from=-1){I fork=T0+first*DT;if(from<0)from=first;Output out;for(int i=from;i<=last;++i){I t=T0+i*DT;if(fixes&&i%2==0)require(f.pipe.fix(1,t,t,observation_lla(branch(f,fork,t,2.563))),"branch fix");out=f.tick(i);}return out;}
int main(){
 test("isolated signed outliers never imply departure",[]{for(double shift:{-12.,12.}){auto f=offmap(10.);f.through(79);double maxerr=0.;for(int i=80;i<=502;++i){I t=T0+i*DT;if(i<=100&&i%2==0)require(f.pipe.fix(1,t,t,f.fix_lla(1,t,0.,i==100?shift:0.)),"fix");auto o=f.tick(i);require(!(o.flags&256),"isolated spike caused free mode");maxerr=std::max(maxerr,norm(sub(o.position,Vec3{{f.start+5.*i*.05,0.,0.}})));}require(maxerr<=3.01,"spike amplified");}});
 test("parallel offset keeps map mode",[]{auto a=offmap(10.),b=offmap(0.);a.through(399);b.through(399);for(int i=400;i<=520;++i){I t=T0+i*DT;if(i%2==0)for(auto*f:{&a,&b})require(f->pipe.fix(1,t,t,f->fix_lla(1,t,0.,12.)),"parallel fix");auto x=a.tick(i),y=b.tick(i);require(!(x.flags&256)&&x.position==y.position,"parallel offset left map");}});
 test("clean departure still tracks course",[]{auto a=offmap(10.);a.through(399);drive_branch(a,400,540);auto x=drive_branch(a,400,600,false,541);require(x.flags&256,"true departure not detected");auto truth=branch(a,T0+400*DT,T0+600*DT,0.);near(norm(sub(x.position,truth)),0.,.25,"branch position");});
 test("outlier during bridge does not replace anchor",[]{auto a=offmap(10.),b=offmap(10.);a.through(399);b.through(399);drive_branch(a,400,540);drive_branch(b,400,540);I t=T0+542*DT;auto xyz=branch(a,T0+400*DT,t,2.563);xyz[1]+=20.;require(a.pipe.fix(1,t,t,observation_lla(xyz)),"fix queued");for(int i=541;i<=600;++i){auto x=a.tick(i),y=b.tick(i);near(norm(sub(x.position,y.position)),0.,1e-9,"bridge polluted");}});
 test("expiry remains continuous and observable",[]{auto a=offmap(10.,20.);a.through(399);auto previous=drive_branch(a,400,540);require(previous.flags&256,"no bridge");bool returned=false;double jump=0.;for(int i=541;i<=700;++i){auto x=a.tick(i);jump=std::max(jump,norm(sub(x.position,previous.position)));if(!(x.flags&256)){returned=true;require(x.flags&512,"return not observable");}previous=x;}require(returned,"no expiry");require(jump<2.,"hard return jump");});
 test("reset clears bridge and return state",[]{auto a=offmap(10.,20.);a.through(399);drive_branch(a,400,540);for(int i=541;i<=700;++i)a.tick(i);a.pipe.reset();auto x=a.tick(0);require(!(x.flags&(256|512)),"mode survived reset");});
 test("no late GNSS is baseline exact",[]{auto a=offmap(10.),b=offmap(0.);for(int i=0;i<=700;++i){auto x=a.tick(i),y=b.tick(i);require(x.velocity==y.velocity&&x.distance==y.distance&&x.position==y.position&&x.flags==y.flags,"absent GNSS changed");}});
 std::cout<<"ROBUST_OFFMAP_RESULT failures="<<failures<<'\n';return failures?1:0;
}
