#include "previous_scenarios.hpp"
void expiry_recovery(bool enabled){auto f=configured(enabled);f.through(399);double maxpost=0.;int resumeaccepted=-1;for(int i=400;i<=1480;++i){I t=T0+i*DT;double s=(i-400)*.25;auto p=returning(s);if((i<=560||i>=1080)&&i%2==0)for(int ch=0;ch<2;++ch)require(f.pipe.fix(ch,t,t,obs(p,ch)),"recovery fix queued");auto o=f.tick(i);double error=norm(sub(o.position,p.p));if(i>=1080)maxpost=std::max(maxpost,error);if(i==560)resumeaccepted=int(o.gnss_accepted);if(i==1079||i==1080||i==1160||i==1280||i==1480)std::cout<<"expiry_recovery enabled="<<enabled<<" tick="<<i<<" error="<<error<<" flags="<<o.flags<<" accepted="<<o.gnss_accepted<<" rejected="<<o.gnss_rejected<<" accepted_before_gap="<<resumeaccepted<<"\n";}std::cout<<"SUMMARY expiry_recovery enabled="<<enabled<<" maximum_after_resumption="<<maxpost<<"\n";}
void quarantine_reset(){auto f=configured(true);f.through(79);I t=T0+80*DT;for(int ch=0;ch<2;++ch)require(f.pipe.fix(ch,t,t,f.fix_lla(ch,t,0.,ch==0?12.:0.)),"conflict");auto o=f.tick(80);require(o.flags&1024,"conflict flag");for(int i=81;i<=86;++i){I h=T0+i*DT;if(i%2==0)for(int ch=0;ch<2;++ch)require(f.pipe.fix(ch,h,h,f.fix_lla(ch,h)),"good pair");o=f.tick(i);if(i==82||i==84)require(o.flags&1024,"cleared before three pairs");if(i==86)require(!(o.flags&1024),"did not clear after three pairs");}std::cout<<"PASS quarantine_three_distinct_pairs\n";
// Recreate conflict, then reset and compare to a fresh engine.
t=T0+88*DT;for(int ch=0;ch<2;++ch)require(f.pipe.fix(ch,t,t,f.fix_lla(ch,t,0.,ch==0?12.:0.)),"second conflict");f.tick(87);require(f.tick(88).flags&1024,"second flag");f.pipe.reset();f.index=-1;auto g=configured(true);for(int i=0;i<=620;++i){I h=T0+i*DT;if(i>=400&&i%2==0)for(auto*z:{&f,&g})for(int ch=0;ch<2;++ch)require(z->pipe.fix(ch,h,h,obs(fake((i-400)*.25),ch)),"reset branch");auto a=f.tick(i),b=g.tick(i);require(a.position==b.position&&a.velocity==b.velocity&&a.distance==b.distance&&a.flags==b.flags&&a.gnss_accepted==b.gnss_accepted&&a.gnss_rejected==b.gnss_rejected,"reset differs");}std::cout<<"PASS reset_conflict_then_branch\n";}
void future_mate(){auto a=configured(true),b=configured(true);for(int i=0;i<=540;++i){I h=T0+i*DT;if(i>=400&&i%2==0)for(auto*f:{&a,&b})for(int ch=0;ch<2;++ch)require(f->pipe.fix(ch,h,h,obs(fake((i-400)*.25),ch)),"initial branch");a.tick(i);b.tick(i);}I now=T0+541*DT;for(auto*f:{&a,&b})require(f->pipe.fix(0,now,now,obs(fake(141*.25),0)),"present master");auto poison=fake(142*.25);poison.p[1]+=100.;require(b.pipe.fix(1,now+DT,now,obs(poison,1)),"future mate queued");auto x=a.tick(541),y=b.tick(541);require(x.position==y.position&&x.flags==y.flags&&x.gnss_accepted==y.gnss_accepted&&x.gnss_rejected==y.gnss_rejected,"future mate affected prefix");std::cout<<"PASS future_mate_prefix\n";}
void height_rejoin(){auto f=configured(true);f.through(399);for(int i=400;i<=1280;++i){I t=T0+i*DT;auto truth=wide_return((i-400)*.25);if(i%2==0)for(int ch=0;ch<2;++ch){auto measured=truth;measured.p[2]+=5.;require(f.pipe.fix(ch,t,t,obs(measured,ch)),"height biased GNSS");}auto o=f.tick(i);if(i==1000||i==1280)std::cout<<"height_rejoin tick="<<i<<" error="<<norm(sub(o.position,truth.p))<<" flags="<<o.flags<<" route_s="<<o.route_s<<" truth_map_x="<<truth.p[0]<<"\n";}}
int main(){std::cout<<std::setprecision(17);previous_scenarios();expiry_recovery(false);expiry_recovery(true);quarantine_reset();future_mate();height_rejoin();}

